FROM  ubuntu
MAINTAINER lupoy

RUN apt update
RUN apt upgrade -y
RUN apt install software-properties-common -y
RUN apt install build-essential -y
RUN apt install wget -y
RUN apt install vim -y
RUN apt install git -y
RUN apt-get install python3-pip -y
RUN pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
RUN pip3 install torchvision
